#create a config map with this command: kubectl create -f agent1-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-properties
#data:
#   agent_start: "o"
#   agent_finish: "x"
#   name: "agent1"
data:
  maze_config.yaml: |
    map: |
      ##############################
      #   a     #              #   #
      # ####    ########        #  #
      #    #    #           b  #   #
      #    ###     #####  ######   #
      #      #   ###   #           #
      #  o   #     #   #  #  #   ###
      #     #####    #    #  # x   #
      #              #       #     #
      ##############################
    agent_config:
      - name: "agent1"
        start: "o"
        finish: "x"
        path_indicator: "*"
      - name: "agent2"
        start: "a"
        finish: "b"
        path_indicator: "."
    output_dir: "/usr/output"
