apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
#  hostPath:
#    path: "/c/Astar/data"
